"""fixed uuid

Revision ID: 501865e9a798
Revises: 4f6e88ab846e
Create Date: 2025-04-19 17:03:23.212136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501865e9a798'
down_revision: Union[str, None] = '4f6e88ab846e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('owner_uuid', sa.UUID(), nullable=False))
    op.drop_constraint('tasks_owner_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['owner_uuid'], ['uuid'])
    op.drop_column('tasks', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_owner_id_fkey', 'tasks', 'users', ['owner_id'], ['uuid'])
    op.drop_column('tasks', 'owner_uuid')
    # ### end Alembic commands ###
