"""changed field 'is_active' to 'used' for RefreshTocken

Revision ID: 6e0b9af62442
Revises: c420a5be9793
Create Date: 2025-05-04 16:47:51.702235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0b9af62442'
down_revision: Union[str, None] = 'c420a5be9793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'used_at')
    # ### end Alembic commands ###
