"""changed field 'is_active' to 'used' for RefreshTocken

Revision ID: a567a43ec744
Revises: ac540f531eb1
Create Date: 2025-05-03 14:34:24.517939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a567a43ec744'
down_revision: Union[str, None] = 'ac540f531eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('used', sa.Boolean(), nullable=False))
    op.drop_column('refresh_tokens', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('refresh_tokens', 'used')
    # ### end Alembic commands ###
