"""created index for token & user_uuid

Revision ID: c420a5be9793
Revises: a567a43ec744
Create Date: 2025-05-03 19:26:30.018026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c420a5be9793'
down_revision: Union[str, None] = 'a567a43ec744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_refresh_tokens_token_user', 'refresh_tokens', ['token', 'user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_token_user', table_name='refresh_tokens')
    # ### end Alembic commands ###
