{
 "title": "Task Manager",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": "label_values(http_requests_total, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests per Second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$app_name\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Requests Count by Method/Handler",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{job=\"$app_name\"}",
     "legendFormat": "{{method}} {{handler}} {{status}}"
    }
   ]
  },
  {
   "title": "Requests Average Latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{job=\"fastapi\"}[1m])) by (handler)\r\n/\r\nsum(rate(http_request_duration_seconds_count{job=\"fastapi\"}[1m])) by (handler)\r\n* 1000\r\n",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "P99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"$app_name\"}[1m])) by (le)) * 1000",
     "legendFormat": "P99 Latency"
    }
   ]
  },
  {
   "title": "Requests In Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_inprogress{job=\"fastapi\"}",
     "legendFormat": "In Progress"
    }
   ]
  },
  {
   "title": "Request Per Second by Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"$app_name\"}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Log of All FastAPI App",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker-logs\", container_name=\"fastapi_task_manager\"} | json | line_format `{{.log}}`\r\n"
    }
   ]
  }
 ]
}